# Generated by Django 5.2.1 on 2026-03-26 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('sex', models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('castrado', 'Castrado')], max_length=20)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('history', models.TextField(blank=True)),
                ('feeding_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caballo',
                'verbose_name_plural': 'Caballos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('issue_type', models.CharField(choices=[('revision', 'Revisión'), ('vacuna', 'Vacuna'), ('desparasitacion', 'Desparasitación'), ('cojera', 'Cojera'), ('colico', 'Cólico'), ('herida', 'Herida'), ('otro', 'Otro')], max_length=30)),
                ('observations', models.TextField(blank=True)),
                ('veterinarian', models.CharField(blank=True, max_length=120)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='horses.horse')),
            ],
            options={
                'verbose_name': 'Registro de salud',
                'verbose_name_plural': 'Registros de salud',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('vacuna', 'Vacuna'), ('herrador', 'Herrador'), ('desparasitacion', 'Desparasitación'), ('veterinario', 'Veterinario'), ('revision', 'Revisión general')], max_length=30)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='horses.horse')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('training_type', models.CharField(choices=[('doma', 'Doma'), ('paseo', 'Paseo'), ('salto', 'Salto'), ('cuerda', 'Cuerda'), ('campo', 'Campo'), ('descanso_activo', 'Descanso activo')], max_length=30)),
                ('duration', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('notes', models.TextField(blank=True)),
                ('intensity', models.CharField(blank=True, max_length=50)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='horses.horse')),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamientos',
                'ordering': ['-date'],
            },
        ),
    ]
